# -*- coding: utf-8 -*-
"""APP.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZOU-IZRl6X0bFojyvzD5mFQCdtSANY3
"""

import streamlit as st
import pandas as pd
import folium
from streamlit_folium import st_folium

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="Smart Bin Analytics Dashboard",
    page_icon="🗑️",
    layout="wide"
)

# --- CUSTOM CSS FOR TILED LOOK (Power BI Style) ---
st.markdown("""
    <style>
    .main { background-color: #f0f2f6; }
    div[data-testid="metric-container"] {
        background-color: white;
        padding: 15px;
        border-radius: 10px;
        box-shadow: 2px 2px 5px rgba(0,0,0,0.1);
        border: 1px solid #e6e9ef;
    }
    .stDataFrame {
        background-color: white;
        padding: 10px;
        border-radius: 10px;
    }
    </style>
    """, unsafe_allow_html=True)

# --- 1. DATA LOADING ---
@st.cache_data
def load_data():
    try:
        # Looks for the CSV file in your GitHub repository
        df = pd.read_csv('smart_bin_data.csv')

        # Date conversion fix
        df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
        df = df.dropna(subset=['timestamp'])
        return df
    except Exception:
        # Fallback dummy data if file is missing (for testing)
        data = {
            'bin_id': ['Bin_01', 'Bin_02', 'Bin_03', 'Bin_04', 'Bin_05'],
            'lat': [19.0760, 19.0850, 19.0950, 19.0780, 19.1000],
            'lon': [72.8777, 72.8850, 72.8950, 72.8600, 72.8800],
            'fill_level': [85, 20, 95, 45, 70],
            'status': ['Full', 'Empty', 'Full', 'Half', 'Half'],
            'timestamp': pd.to_datetime(['2025-12-19']*5)
        }
        return pd.DataFrame(data)

df = load_data()

# --- 2. SIDEBAR (Power BI Slicers) ---
st.sidebar.header("Dashboard Filters")
st.sidebar.markdown("---")
# Slider to filter bins by fill level
min_fill = st.sidebar.slider("Min Fill Level (%)", 0, 100, 0)
# Multi-select for specific bins
selected_bins = st.sidebar.multiselect("Select Specific Bins", options=df['bin_id'].unique(), default=df['bin_id'].unique())

# Apply Filters
filtered_df = df[(df['fill_level'] >= min_fill) & (df['bin_id'].isin(selected_bins))]

# --- 3. MAIN DASHBOARD UI ---
st.title("📊 Smart Bin Management System")
st.markdown(f"Last updated: **{df['timestamp'].max()}**")

# KPI Metrics Row
kpi1, kpi2, kpi3, kpi4 = st.columns(4)

total_bins = len(filtered_df)
avg_fill = filtered_df['fill_level'].mean() if not filtered_df.empty else 0
critical_bins = len(filtered_df[filtered_df['fill_level'] >= 80])

kpi1.metric("Total Bins Monitored", total_bins)
kpi2.metric("Average Fill %", f"{avg_fill:.1f}%")
kpi3.metric("Critical Bins (>80%)", critical_bins, delta=critical_bins, delta_color="inverse")
kpi4.metric("System Health", "Active", delta="Stable")

st.divider()

# Layout: Map on left, Chart/Table on right
col_left, col_right = st.columns([2, 1.2])

with col_left:
    st.subheader("📍 Real-time Bin Locations")
    # Initialize Map centered on the average location
    if not filtered_df.empty:
        m = folium.Map(location=[filtered_df['lat'].mean(), filtered_df['lon'].mean()], zoom_start=13, tiles="cartodbpositron")

        for i, row in filtered_df.iterrows():
            # Marker color based on fill level
            marker_color = 'red' if row['fill_level'] >= 80 else ('orange' if row['fill_level'] >= 50 else 'green')

            folium.Marker(
                location=[row['lat'], row['lon']],
                popup=f"Bin: {row['bin_id']} | Fill: {row['fill_level']}%",
                tooltip=row['bin_id'],
                icon=folium.Icon(color=marker_color, icon='trash', prefix='fa')
            ).add_to(m)

        st_folium(m, width="100%", height=500)
    else:
        st.warning("No data matches the selected filters.")

with col_right:
    st.subheader("📈 Fill Level Analysis")
    st.bar_chart(filtered_df, x="bin_id", y="fill_level", color="#1f77b4")

    st.subheader("📋 Status Summary")
    # Styling the status table
    st.dataframe(
        filtered_df[['bin_id', 'fill_level', 'timestamp']].sort_values(by='fill_level', ascending=False),
        use_container_width=True,
        hide_index=True
    )

# --- FOOTER ---
st.markdown("---")
st.caption("Smart City Project | Powered by Streamlit & IoT")
